// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhcfekvwgwkserojonmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoY2Zla3Z3Z3drc2Vyb2pvbm1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2ODc3MTUsImV4cCI6MjA2MjI2MzcxNX0.gtNMAWBQZOIkW6NTnKrk2eqiTHdweJFcrpUG1DzvZpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);